### PR TITLE
super so @fields is not nil during #define_setters

### PR DESCRIPTION
**Pull request by ahoward**
unsure how tests could be passing for anyone w/o this but it is definitely needed - or the management mixin a re-designed strategy

### CODE REVIEW

**Comment by dlitvakb** [comment]
Thanks @ahoward,

I'll take a look at it as soon as I can, seems like I forgot to re-add it (at some point I'm 100% sure I put it in there)

Cheers

**Comment by ahoward** [comment]
👍

**Comment by ahoward** [comment]
bumpity?

**Comment by dlitvakb** [comment]
Hey @ahoward,

Sorry for the delay, I was at RailsConf and traveling abroad took most of my time last week.

Adding this now

Cheers

**Pull request merged**
